name: Python package

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test
          create-args: >-
            python=${{ matrix.python-version }}
            cartopy
            geopandas
            numba
            spatialpandas
            pytest
            pytest-cov
            ruff
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py38 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py38 .
      - name: Test with pytest
        run: |
          pytest
